### ISSUE TITLE
cgMLST schema for C.jejuni missing in chewbie-NS server

### ISSUE THREAD

**Issue by bala-ruokavirasto** [B-UMMI/Chewie-NS#22]
Hi,

I only find the wgMLST schemas in the chewbie-NS server. Can you kindly let me know where I can find the cgMLST schemas for C.jejuni ? If not available, then kindly let us know the genomes used and I will try to find the cgMLST from it.

Best Regards,
Bala

**Comment by rfm-targa** [comment]
Hello @bala-ruokavirasto,

I believe this has been answered in issue B-UMMI/chewBBACA#101 that you opened in chewBBACA's repo.
I will close this issue, but let us know if there is anything else.

Best regards,
Rafael

**Comment by bala-ruokavirasto** [comment]
Dear Chewie-NS team,

Is there any metadata (eg. Source, Year, etc..) related to historical data associated with the genomes used for the construction of external schema?

If so then kindly let us know so that we can able make use of it as in the innuendo project link below:

https://innuendo.readthedocs.io/en/latest/usage/set-legacy.html

I am attaching a reference metadata file for your reference where each row is a assembled genome of an isolate.

Yenterocolitica_metadata.txt

Kindly let us know the possibilities!

Best Regards,
Bala
