### ISSUE TITLE
[Question] Why are the genes renamed from external schemes

### ISSUE THREAD

**Issue by dutchscientist** [B-UMMI/Chewie-NS#7]
Am looking at the schemes available via chewie-NS. Great initiative, but why have the genes been renamed? For instance, the Listeria one now has gene codes like "Pasteur_cgMLST-00089108.fasta", rather than the Pasteur LmoXXXX codes. Is there a conversion table? I noticed the same for the E. coli, Salmonella and Campylobacter ones.

**Comment by pedrorvc** [comment]
Hello @dutchscientist
The genes have been renamed to have a unique label for Chewie-NS' database. We are working on a solution to include the original gene names.

Thank you for bringing this our attention.

Cheers,
Pedro

**Comment by dutchscientist** [comment]
Ah, thanks, that makes sense. Probably easiest to solve by including a conversion table? :)

**Comment by pedrorvc** [comment]
Hi @dutchscientist,
We added a new column to the Locus Information table containing the original gene names. 

Let us know if this solves your issue.

Cheers,
Pedro

**Comment by ramirma** [comment]
Just to add quickly to what @pedrorvc has written, you can download a CSV with the information from the relevant table in chewie-NS. Let us know if this works for you @dutchscientist

**Comment by dutchscientist** [comment]
Thanks, will check. Sorry for slow response!
